### ISSUE TITLE
`requirements.txt` (or `Pipfile`) missing

### ISSUE THREAD

**Issue by gh640** [c-c-l/DatAsana#1]
I tried the `index.html` and it looks nice.

I believe adding `requirements.txt` (or more modern `Pipfile`) makes it easier for others to run the `.py` script in this repo easier. For example:

`requirements.txt`:

```
beautifulsoup4==4.6.0
```

`Pipfile`:

```
[[source]]
url = "https://pypi.org/simple"
verify_ssl = true
name = "pypi"

[packages]
"beautifulsoup4" = "*"

[dev-packages]

[requires]
python_version = "3.6"
```

**Comment by c-c-l** [comment]
Thanks Goto-san :+1:
